//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALC.IES.WebRange.DataLayer.JDEdwardsService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JDEdwardsService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EjecutarConsulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EjecutarConsulta(string sSelect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EjecutarConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EjecutarConsultaAsync(string sSelect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EjecutarActualizacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EjecutarActualizacion(string sComando);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EjecutarActualizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EjecutarActualizacionAsync(string sComando);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrefijo1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPrefijo1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrefijo1", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPrefijo1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrefijo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPrefijo2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrefijo2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPrefijo2Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ALC.IES.WebRange.DataLayer.JDEdwardsService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ALC.IES.WebRange.DataLayer.JDEdwardsService.Service1Soap>, ALC.IES.WebRange.DataLayer.JDEdwardsService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet EjecutarConsulta(string sSelect) {
            return base.Channel.EjecutarConsulta(sSelect);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EjecutarConsultaAsync(string sSelect) {
            return base.Channel.EjecutarConsultaAsync(sSelect);
        }
        
        public bool EjecutarActualizacion(string sComando) {
            return base.Channel.EjecutarActualizacion(sComando);
        }
        
        public System.Threading.Tasks.Task<bool> EjecutarActualizacionAsync(string sComando) {
            return base.Channel.EjecutarActualizacionAsync(sComando);
        }
        
        public string GetPrefijo1() {
            return base.Channel.GetPrefijo1();
        }
        
        public System.Threading.Tasks.Task<string> GetPrefijo1Async() {
            return base.Channel.GetPrefijo1Async();
        }
        
        public string GetPrefijo2() {
            return base.Channel.GetPrefijo2();
        }
        
        public System.Threading.Tasks.Task<string> GetPrefijo2Async() {
            return base.Channel.GetPrefijo2Async();
        }
    }
}
